server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jackson:
    date-format: yyyy/MM/dd HH:mm
    time-zone: Asia/Seoul
  profiles:
    active: deploy

# Python AI API 설정
python:
  api:
    url: http://localhost:8000
    single:
      endpoint: /v1/rewrite-summarize
    batch:
      endpoint: /v1/rewrite-batch
    chat:
      endpoint: /v1/chat-article